---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    rpi_url: http://goldyfruitr01.vpnplus.to:3000

  tasks:
    - name: Retrieve indoor temperature
      uri:
        url: "{{ rpi_url }}/temperature"
        return_content: yes
      register: data

    - name: Display value
      debug:
        var: data
